# Generated by Django 3.2 on 2022-02-03 11:28

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('char_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('series', models.CharField(default='unknown', max_length=100)),
                ('first_published', models.DateTimeField(auto_now_add=True)),
                ('first_aired', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(default='Enter bio here', max_length=300)),
                ('good_reason', models.CharField(default='', max_length=100)),
                ('bad_reason', models.CharField(default='', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('likes', models.ManyToManyField(blank=True, related_name='character_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'series'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charcater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='collection.character')),
            ],
        ),
    ]
