# Generated by Django 3.2 on 2022-02-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('series_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['series_name', 'name']},
        ),
        migrations.RenameField(
            model_name='character',
            old_name='series',
            new_name='series_name',
        ),
    ]
