# Generated by Django 3.2 on 2022-02-03 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20220203_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['series_name']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='charcater',
            new_name='character',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='e@mail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='name', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='series_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='collection.series'),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.IntegerField(choices=[(0, 'Hidden'), (1, 'Displayed')], default=0),
        ),
    ]
