# Generated by Django 3.2 on 2022-02-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_series_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='first_aired',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='first_published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
