# Generated by Django 3.2 on 2022-02-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20220203_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='bio',
            field=models.TextField(default='Enter bio here', max_length=1000),
        ),
    ]
