# Generated by Django 3.2 on 2022-02-05 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0006_alter_character_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='likes',
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_sug', models.CharField(max_length=100)),
                ('series_sug', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_when'],
            },
        ),
    ]
