# Generated by Django 3.2 on 2022-02-06 20:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_character_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='series_logo',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='character',
            name='bio',
            field=models.TextField(default='Enter bio here', max_length=4000),
        ),
    ]
