# Generated by Django 3.2 on 2022-02-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_auto_20220206_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='bio',
            field=models.TextField(default='Enter bio here', max_length=2000),
        ),
        migrations.AlterField(
            model_name='character',
            name='first_aired',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='first_published',
            field=models.DateField(blank=True),
        ),
    ]
