# Generated by Django 3.2 on 2022-02-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20220206_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='bio',
            field=models.TextField(default='Enter bio here', max_length=4000),
        ),
    ]
