# Generated by Django 3.2 on 2022-02-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_alter_character_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.IntegerField(choices=[(0, 'Hidden'), (1, 'Displayed')], default=1),
        ),
    ]
