# Generated by Django 3.2 on 2022-02-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_alter_character_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='bio',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='character',
            name='special',
            field=models.CharField(max_length=200),
        ),
    ]
