# Generated by Django 3.2 on 2022-02-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_auto_20220209_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='bio',
            field=models.TextField(default='', max_length=4000),
        ),
    ]
