# Generated by Django 3.2 on 2022-02-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_alter_series_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='created_by',
        ),
    ]
