# Generated by Django 3.2 on 2022-02-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0018_remove_suggestion_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='char_sug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
