# Generated by Django 3.2 on 2022-02-10 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0019_alter_suggestion_char_sug'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='sug_type',
            field=models.IntegerField(choices=[(0, 'character'), (1, 'series')], default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
