# Generated by Django 3.2 on 2022-02-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0020_auto_20220210_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='sug_type',
            field=models.IntegerField(choices=[(0, 'Character'), (1, 'Series')], default=1),
        ),
    ]
