# Generated by Django 3.2 on 2022-02-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0022_series_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='slug',
        ),
    ]
