# Generated by Django 3.2 on 2022-02-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0024_auto_20220216_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='char_rating',
        ),
    ]
