# Generated by Django 3.2 on 2022-02-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0025_remove_character_char_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
