# Generated by Django 3.2 on 2022-02-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0026_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
