# Generated by Django 3.2 on 2022-02-16 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0028_alter_comment_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
