# Generated by Django 3.2 on 2022-02-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0031_alter_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='votes',
        ),
    ]
