# Generated by Django 3.2 on 2022-02-19 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0032_remove_character_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_ratings', to='collection.character')),
                ('votes', models.ManyToManyField(blank=True, related_name='char_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
