# Generated by Django 3.2 on 2022-02-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0033_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
