# Generated by Django 3.2 on 2022-02-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0034_alter_rating_stars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
