# Generated by Django 3.2 on 2022-02-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0035_delete_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='series',
            name='approved',
        ),
    ]
